id: PB7F878B9
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA00KG0622
  instance_id: http://purl.bdrc.io/resource/IE00KG0622
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བོད་ཀྱི་སྲོལ་རྒྱུན་རིག་གནས་དང་དེང་དུས་ཀྱི་ཁོར་ཡུག་སྲུང་སྐྱོབ།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - zang zhu chuan tong wen hua yu bao hu
  author: http://purl.bdrc.io/resource/P00KG0637
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    258eb9d9be27453c90ec7558cc2fb456:
      title: པོད ༡་བོད་ཀྱི་སྲོལ་རྒྱུན་རིག་གནས་དང་དེང་དུས་ཀྱི་ཁོར་ཡུག་སྲུང་སྐྱོབ
      volume_number: 1
      base_file: UT00KG0622_I1PD28046_0000.txt
      reference: http://purl.bdrc.io/resource/VLC42CD0F553087E59
      image_group: I1PD28046
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W00KG0622
  - http://purl.bdrc.io/resource/MW00KG0622
  ocr_software: Namsel
created_at: '2021-12-22T10:16:42.804999'
last_modified_at: '2021-12-22T10:16:42.805004'
statistics:
  total_words: 110219
  total_non_words: 18323
quality:
  non_words_ratio: 0.17
